### ISSUE TITLE
Some incompletness in sources

### ISSUE THREAD

**Issue by zamazan4ik** [CallOfCrutches/omp_utils#1]
Hi! 
I've just find your utilities. Seems like you've missed some sources in repo. Can you add them please? Without them I cannoy use your pretty utils. E.g. I cannot find `COmpPtr` and `CComPtr` definitions.

Thank you.

**Comment by CallOfCrutches** [comment]
Hi! Thanks for your kind words. I'm sorry for that inconvinience. I added examples, so you could see how to use theses utils if you're still interested in them.
